#!/usr/bin/env bash

west build \
  --pristine \
  --source zmk/app \
  --board nice_nano_v2 \
  -- \
  -DSHIELD="arch36_left" \
  -DCONFIG_ZMK_KEYBOARD_NAME="\"Arch36T\"" \
  -DZMK_CONFIG=/root/config \
  && \
  BOARD=arch36t_left ./scripts/postprocess_firmware

west build \
  --pristine \
  --source zmk/app \
  --board nice_nano_v2 \
  -- \
  -DSHIELD="arch36_right" \
  -DZMK_CONFIG=/root/config \
  && \
  BOARD=arch36t_right ./scripts/postprocess_firmware
