#!/usr/bin/env bash

declare -a SIDES=("left" "right")

for SIDE in "${SIDES[@]}"; do
	west build \
		--pristine \
		--source zmk/app \
		--board "corneish_zen_v2_${SIDE}" \
		-- \
		-DZMK_CONFIG=/root/config &&
		BOARD=${BOARD}_${SIDE} ./scripts/postprocess_firmware
done
